//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronalNetwork.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronalNetwork.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Network xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xsi:type=&quot;ActivationNetwork&quot;&gt;
        ///  &lt;InputsCount&gt;2&lt;/InputsCount&gt;
        ///  &lt;LayersCount&gt;1&lt;/LayersCount&gt;
        ///  &lt;Layers&gt;
        ///    &lt;Layer xsi:type=&quot;ActivationLayer&quot;&gt;
        ///      &lt;Neurons&gt;
        ///        &lt;Neuron xsi:type=&quot;ActivationNeuron&quot;&gt;
        ///          &lt;InputsCount&gt;2&lt;/InputsCount&gt;
        ///          &lt;ActivationFunction xsi:type=&quot;ThresholdFunction&quot; /&gt;
        ///          &lt;Weights&gt;
        ///            &lt;double&gt;0.57&lt;/doub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Network xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xsi:type=&quot;ActivationNetwork&quot;&gt;
        ///  &lt;InputsCount&gt;2&lt;/InputsCount&gt;
        ///  &lt;LayersCount&gt;2&lt;/LayersCount&gt;
        ///  &lt;Layers&gt;
        ///    &lt;Layer xsi:type=&quot;ActivationLayer&quot;&gt;
        ///      &lt;Neurons&gt;
        ///        &lt;Neuron xsi:type=&quot;ActivationNeuron&quot;&gt;
        ///          &lt;InputsCount&gt;2&lt;/InputsCount&gt;
        ///          &lt;ActivationFunction xsi:type=&quot;ThresholdFunction&quot; /&gt;
        ///          &lt;Weights&gt;
        ///            &lt;double&gt;6.54&lt;/doub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xor {
            get {
                return ResourceManager.GetString("xor", resourceCulture);
            }
        }
    }
}
